// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpmfbdKJmHi-BBZrJPHeL2NmF-PjijIgc',
    appId: '1:481691224180:web:d89d0d5181ce853d042921',
    messagingSenderId: '481691224180',
    projectId: 'test-3be58',
    authDomain: 'test-3be58.firebaseapp.com',
    storageBucket: 'test-3be58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCJQe8zYziTFUBabmyTo-gD7D1vIgiRPA',
    appId: '1:481691224180:android:b01677046b3d8102042921',
    messagingSenderId: '481691224180',
    projectId: 'test-3be58',
    storageBucket: 'test-3be58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKLKP686mOck8qTztg6ZKuKDUMPXi5fuQ',
    appId: '1:481691224180:ios:441b1bb8d75e80ba042921',
    messagingSenderId: '481691224180',
    projectId: 'test-3be58',
    storageBucket: 'test-3be58.appspot.com',
    iosClientId: '481691224180-sohh0g2gsuhce4ihtce6mst5cdve63im.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKLKP686mOck8qTztg6ZKuKDUMPXi5fuQ',
    appId: '1:481691224180:ios:441b1bb8d75e80ba042921',
    messagingSenderId: '481691224180',
    projectId: 'test-3be58',
    storageBucket: 'test-3be58.appspot.com',
    iosClientId: '481691224180-sohh0g2gsuhce4ihtce6mst5cdve63im.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
